name: talk_shawlk
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For using cupertino icons
  cupertino_icons: ^1.0.2

  # FIREBASE AND AUTH
  firebase_core: ^2.2.0

  firebase_auth: ^4.1.3

  google_sign_in: ^5.4.2

  cloud_firestore: ^4.1.0

  firebase_storage: ^11.0.6

  firebase_messaging: ^14.2.0

  # GENERAL
  cached_network_image: ^3.2.3

  image_picker: ^0.8.6

  emoji_picker_flutter: ^1.5.1

  # INTERNET CALLS
  http: ^0.13.5

  # CUSTOM NOTIFICATION
  flutter_notification_channel: ^2.0.0

  # For storing images into gallery
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For recommended coding practices
  flutter_lints: ^2.0.0

flutter:
  # For enabling material design
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
