// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIK-AwtWo7ifZBMJabV4R1L4D-5IA7jWQ',
    appId: '1:592703648750:android:ef71d3622b93c411d654ff',
    messagingSenderId: '592703648750',
    projectId: 'talkshawlk-31cbe',
    storageBucket: 'talkshawlk-31cbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-q-NP8w5P2fScH_2WtTbumlWs5jwKKTk',
    appId: '1:592703648750:ios:4b9e2d2826425dead654ff',
    messagingSenderId: '592703648750',
    projectId: 'talkshawlk-31cbe',
    storageBucket: 'talkshawlk-31cbe.appspot.com',
    androidClientId: '592703648750-0gjk2a7014srcvpfb9l66ai2u5eb1lds.apps.googleusercontent.com',
    iosClientId: '592703648750-jpadlu089206rvvkem88je9gmnrpjs8h.apps.googleusercontent.com',
    iosBundleId: 'com.owais.talkshawlk',
  );
}
